ARG BUILD_ENV="build:dev"
ARG SUITE_BRANCH=suite
ARG WALLET_BRANCH=suite
ARG VOTING_BRANCH=suite

FROM node:20 as stage-explorer
ARG BUILD_ENV
WORKDIR /app/camino-block-explorer

COPY ./ /app/camino-block-explorer/
RUN yarn install
RUN yarn $BUILD_ENV


FROM public.ecr.aws/n0m7j6i5/camino-suite-host:$SUITE_BRANCH as stage-suite


FROM public.ecr.aws/n0m7j6i5/camino-suite-wallet:$WALLET_BRANCH  as stage-wallet

FROM public.ecr.aws/n0m7j6i5/camino-suite-voting:$VOTING_BRANCH  as stage-voting



FROM nginx:1.18
COPY --from=stage-suite /app/camino-suite/dist/ /usr/share/nginx/html
COPY --from=stage-explorer /app/camino-block-explorer/dist/ /usr/share/nginx/html/explorer
COPY --from=stage-wallet /app/camino-wallet/dist/ /usr/share/nginx/html/wallet
COPY --from=stage-voting /app/camino-suite-voting/dist/ /usr/share/nginx/html/dac
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY ./nginx.conf /etc/nginx/conf.d/default.conf